<?xml version="1.0" encoding="utf-8"?>
<XmlCompilation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Url>C:\PROJECTS\codeplex\replayer\TestCompilations\lammfromm\lammfromm.xml</Url>
  <Tracks>
    <Track>
      <Cues>
        <Cue>
          <Id>57392192-3dab-4902-bad3-9f98edc713d6</Id>
          <Description>Intro (autogenerated)</Description>
          <Shortcut>1</Shortcut>
          <Time>0</Time>
        </Cue>
        <Cue>
          <Id>76848511-fc8b-4d95-8394-cc4be2a2c8f5</Id>
          <Description>Cue at 00:00:10.4374399 seconds</Description>
          <Shortcut>2</Shortcut>
          <Time>10.4374399</Time>
        </Cue>
        <Cue>
          <Id>e2973400-0abf-42e5-b2ef-2525a3373796</Id>
          <Description>Cue at 00:00:21.7880771 seconds</Description>
          <Shortcut>3</Shortcut>
          <Time>21.7880771</Time>
        </Cue>
      </Cues>
      <Id>e6e49655-a179-4847-8127-64cf1a151dad</Id>
      <Measure>0</Measure>
      <Url>C:\PROJECTS\codeplex\replayer\TestCompilations\lammfromm\fullofjoy.mp3</Url>
    </Track>
    <Track>
      <Cues>
        <Cue>
          <Id>6b2c2ad7-847c-4c1c-b621-8b24d0cf4efe</Id>
          <Description>Intro (autogenerated)</Description>
          <Shortcut>1</Shortcut>
          <Time>0</Time>
        </Cue>
      </Cues>
      <Id>481c821f-e1a7-46dd-8fe8-80812c38920a</Id>
      <Measure>0</Measure>
      <Url>C:\PROJECTS\codeplex\replayer\TestCompilations\lammfromm\hereistand.mp3</Url>
    </Track>
    <Track>
      <Cues>
        <Cue>
          <Id>33e72eef-19a4-4e1c-97f3-8429b60075d6</Id>
          <Description>Intro (autogenerated)</Description>
          <Shortcut>1</Shortcut>
          <Time>0</Time>
        </Cue>
      </Cues>
      <Id>9b155a59-65e9-4cea-bf40-dadd776bc2d1</Id>
      <Name>imsorry</Name>
      <Measure>0</Measure>
      <Url>C:\PROJECTS\codeplex\replayer\TestCompilations\lammfromm\imsorry.mp3</Url>
    </Track>
  </Tracks>
  <Title>test</Title>
  <Id>b5715982-906c-46a3-a8f8-45c9c46abeac</Id>
</XmlCompilation>