<?xml version="1.0" encoding="utf-8"?>
<XmlCompilation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Url>C:\PROJECTS\codeplex\replayer\TestCompilations\lammfromm\test for forward-backward.xml</Url>
  <Tracks>
    <Track>
      <Cues>
        <Cue>
          <Id>ef31d5c4-9acd-492a-be37-c5e825d97120</Id>
          <Description>Intro (autogenerated)</Description>
          <Shortcut>1</Shortcut>
          <Time>0</Time>
        </Cue>
        <Cue>
          <Id>b1d5af13-67a6-40f8-9e20-10d80b702927</Id>
          <Description>Cue at 00:00:02.6029751 seconds</Description>
          <Shortcut>2</Shortcut>
          <Time>2.6029751</Time>
        </Cue>
        <Cue>
          <Id>0a87cbe2-8968-4e4d-bbd8-81e5c69cbda0</Id>
          <Description>Cue at 00:00:05.6230430 seconds</Description>
          <Shortcut>3</Shortcut>
          <Time>5.623043</Time>
        </Cue>
        <Cue>
          <Id>0fd89c2d-b7ae-4b34-b296-e910655c44b5</Id>
          <Description>Cue at 00:00:13.3243242 seconds</Description>
          <Shortcut>4</Shortcut>
          <Time>13.3243242</Time>
        </Cue>
      </Cues>
      <Id>c9007223-3845-473d-ac4d-bc92947d6136</Id>
      <Name>fullofjoy</Name>
      <Measure>0</Measure>
      <Url>C:\PROJECTS\codeplex\replayer\TestCompilations\lammfromm\fullofjoy.mp3</Url>
    </Track>
    <Track>
      <Cues>
        <Cue>
          <Id>01a6eaf3-6916-4c42-ac57-6b4d68b39b6f</Id>
          <Description>Intro (autogenerated)</Description>
          <Shortcut>1</Shortcut>
          <Time>0</Time>
        </Cue>
        <Cue>
          <Id>31dc891b-fdac-4c44-a1c0-0f1c5687f5a6</Id>
          <Description>Cue at 00:00:04.8207007 seconds</Description>
          <Shortcut>5</Shortcut>
          <Time>4.8207007</Time>
        </Cue>
        <Cue>
          <Id>afcb9a49-68b0-4d8f-b1d7-a8a01722e50c</Id>
          <Description>Cue at 00:00:10.6509071 seconds</Description>
          <Shortcut>6</Shortcut>
          <Time>10.6509071</Time>
        </Cue>
      </Cues>
      <Id>b14fb1cf-4ad3-4fb4-af1f-79aeace80c82</Id>
      <Name>hereistand</Name>
      <Measure>0</Measure>
      <Url>C:\PROJECTS\codeplex\replayer\TestCompilations\lammfromm\hereistand.mp3</Url>
    </Track>
  </Tracks>
  <Id>e987640c-8a49-4c46-93a8-9fbb15f449fe</Id>
</XmlCompilation>